### ISSUE TITLE
"Missing apiURL" on 0.1.0

### ISSUE THREAD

**Issue by ctotzek-md** [currents-dev/currents-nx#9]
Hi, we just (automatically) updated `@currents/nx` from 0.0.7 to 0.1.0 without changing anything else and got this error message: `>  NX   Missing apiURL`.

**Comment by WolfSoko** [comment]
Same Problem here: 
 I found out, that the `apiUrl` patch function of `cy2`  is mandatory: 

So the last change from currents.impl.ts: 

```
  process.env.CYPRESS_API_URL =
    options.cypressApiUrl ?? 'https://cy.currents.dev';

  await patch();

``` 
Cannot work because: 

/**
 * Patch Cypress with a custom API URL.
 *
 * Try to discover the location of `app.yml`
 * and patch it with a custom URL.
 *
 * @param {string} apiURL - new API URL to use
 * @param {string} [cypressConfigFilePath] - explicitly provide the path to Cypress app.yml and disable auto-discovery
 */
export async function patch(apiURL: string, cypressConfigFilePath?: string) {
  if (!apiURL) {
    throw new Error('Missing apiURL');
  }
  
 Api Url is mandatory

**Comment by agoldis** [comment]
@ctotzek-md, @WolfSoko 

The new version was supposed to use cy2@3.2.0+, and it has a breaking change in its `patch` function. 
Working on an update
